name: Scheduled Trigger

on:
  schedule:
    - cron: '0 0 * * *' #Mid Night UTC 
  workflow_dispatch: # Task 3: Manual Trigger
    inputs:
      environment:
        description: 'Environment name (staging/production)'
        required: true
        default: 'staging'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "Running deployment for environment... ${{ inputs.environment }}"
