name: Pre-installed Tools

on:
    workflow_dispatch:

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print info - Ubuntu
              run: |
                echo "OS: ${{ runner.os }}"
                hostname
                whoami
            - name: Pre-Installed Tools
              run: |
                docker --version
                python --version
                node --version
                git --version