name: Secret Management

on:
    workflow_dispatch:

jobs:
    secrets-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Show secret exists
              run: |
                echo "The secret is set: ${{ secrets.MY_SECRET_MESSAGE != ''}}" 

            - name: Try to print secret
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"
