name: Smart Pipeline

on:
    push:
        
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Linting code..."

    test:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Running tests..."

    summary:
        needs: [lint, test]
        name: Summary
        runs-on: ubuntu-latest
        steps:
                - name: Branch Check
                  run: |
                        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
                            echo "This is a MAIN branch push."
                        else
                            echo "This is a FEATURE branch push."
                        fi
                    
                - name: Print Commit Message
                  run: echo "Commit message: ${{ github.event.commits[0].message }}"